services:
  app:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.expo:/root/.expo
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: "192.168.1.23" # <- cambia esto
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "true"
    tty: true
    stdin_open: true
    command: sh -c "npm ci || npm install && npm run start"
